app_usuario:
    resource: "@AppBundle/Controller/UsuarioController.php"
    type:     annotation

app:
    resource: '@AppBundle/Resources/config/app.yml'
    prefix:

admin:
    resource: '@AppBundle/Resources/config/admin.yml'
    prefix: admin/